name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
     - uses: actions/checkout@v2
     - name: Run a one-line script
       run: echo "Hello World"
     - name: Run a multi-line script
       run: |
         echo "Add other actions to build"
         echo "test & deploy your application"
         
     - name: Set up Buildx
       uses: docker/setup-buildx-action@v3.0.0

     - name: Docker Login
       uses: docker/login-action@v3.1.0
       with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
          
     - name: Build and push Docker images
       uses: docker/build-push-action@v5.3.0
       with:
        context: .
        push: true
        tags: ${{secrets.ACR_NAME}}/contoso-website:latest

          
    

          

    
