name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
     - uses: actions/checkout@v2
     - name: Run a one-line script
       run: echo "Hello World"
     - name: Run a multi-line script
       run: |
         echo "Add other actions to build"
         echo "test & deploy your application"

     - name: Fetch latest version
       id: fetch_version
       run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
         
     - name: Set up Buildx
       uses: docker/setup-buildx-action@v3.0.0
       
     - name: Docker Login
       uses: docker/login-action@v3.1.0
       with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
          
     - name: Build and push Docker images
       uses: docker/build-push-action@v5.3.0
       with:
        context: .
        push: true
        tags: ${{secrets.ACR_NAME}}/contoso-website:latest

  deploy:
   runs-on: ubuntu-20.04
   needs: build
   permissions:
     id-token: write
     contents: read

   steps:
     - uses: actions/checkout@v2

     - name: Helm tool installer
       uses: Azure/setup-helm@v3
       with:
          version: v3.3.1

     - name: Sign in to Azure with OIDC
       uses: Azure/login@v1.5.1
       with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

     - name: Kubernetes Set Context
       uses: Azure/k8s-set-context@v3.0
       with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        cluster-name: ${{ secrets.CLUSTER_NAME }}
          
          
          

          
          

     
   

          
    

          

    
